package com.beautifulquran.timingslab

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.widget.Toast
import com.beautifulquran.BuildConfig
import com.beautifulquran.data.model.Reciter
import com.beautifulquran.data.model.Segment
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** One (reciter, surah, ayah) correction, ready to be exported as a patch. */
@Serializable
data class PatchEdit(
    val reciterId: Int,
    val reciterSlug: String,
    val surahId: Int,
    val ayah: Int,
    val segments: List<List<Long>>,
)

/** Full patch payload: a JSON object the maintainer can drop straight into
 * `tools/timing_overrides/{rid}.json` and rebuild with the apply script. */
@Serializable
data class TimingsPatch(
    val schema: Int = 1,
    val device: String,
    val appVersion: String,
    val edits: List<PatchEdit>,
)

object TimingsPatchExporter {

    private const val REPO_NEW_ISSUE_URL =
        "https://github.com/sguergachi/Beautiful-Quran-/issues/new"

    /** Build a [TimingsPatch] from the override store snapshot, grouped per
     * (reciter, surah, ayah) and sorted for review. */
    fun build(
        overrides: Map<OverrideKey, List<Segment>>,
        reciterLookup: (Int) -> Reciter?,
    ): TimingsPatch {
        val edits = overrides.entries
            .sortedWith(
                compareBy({ it.key.reciterId }, { it.key.surahId }, { it.key.ayah }),
            )
            .map { (k, segs) ->
                val reciter = reciterLookup(k.reciterId)
                PatchEdit(
                    reciterId = k.reciterId,
                    reciterSlug = reciter?.slug ?: "unknown",
                    surahId = k.surahId,
                    ayah = k.ayah,
                    segments = segs.map { listOf(it.position.toLong(), it.startMs, it.endMs) },
                )
            }
        return TimingsPatch(
            device = "${Build.MANUFACTURER}/${Build.MODEL}",
            appVersion = BuildConfig.VERSION_NAME,
            edits = edits,
        )
    }

    private val json = Json { prettyPrint = true }

    /** Human-readable body for the new GitHub issue, with the patch under a
     * fenced ```json``` block ready to paste. */
    fun body(patch: TimingsPatch): String = buildString {
        appendLine("Timings patch from device lab — ${patch.edits.size} edited ayah${if (patch.edits.size == 1) "" else "s"}.")
        appendLine()
        appendLine("Generated by the in-app Timings Lab on `${patch.device}` running v${patch.appVersion}.")
        appendLine()
        appendLine("## Apply")
        appendLine()
        appendLine("Drop the JSON under the fence into `tools/timing_overrides/reciter-<id>.json` for each reciter and run:")
        appendLine("`python3 tools/apply_timing_overrides.py && python3 tools/build_db.py`")
        appendLine()
        appendLine("## Verification checklist")
        appendLine()
        appendLine("- [ ] Audible alignment ear-verified against the bundled everyayah audio")
        appendLine("- [ ] Segments are sorted by `start_ms`")
        appendLine("- [ ] Every `position` is in `[1, word_count]`")
        appendLine("- [ ] Backtracks (position ≤ previously-seen max) are intentional repeats, not alignment noise")
        appendLine()
        for (edit in patch.edits) {
            appendLine("- reciter `${edit.reciterSlug}` (id ${edit.reciterId}) — Surah ${edit.surahId} Ayah ${edit.ayah}: ${edit.segments.size} segments")
        }
        appendLine()
        appendLine("```json")
        appendLine(json.encodeToString(TimingsPatch.serializer(), patch))
        appendLine("```")
    }

    private fun title(patch: TimingsPatch): String {
        val first = patch.edits.firstOrNull()
        val tail = if (patch.edits.size == 1) {
            "${first?.reciterSlug} ${first?.surahId}:${first?.ayah}"
        } else {
            "${patch.edits.size} ayahs"
        }
        return "Timings patch — $tail"
    }

    /** Builds an `https://github.com/.../issues/new?title=&body=` deep-link
     * that pre-fills the new-issue form with the patch. Opening this URL via
     * [Intent.ACTION_VIEW] requires no extra permissions and zero backend. */
    fun newIssueIntent(patch: TimingsPatch): Intent {
        val url = buildString {
            append(REPO_NEW_ISSUE_URL)
            append("?title=")
            append(Uri.encode(title(patch)))
            append("&body=")
            append(Uri.encode(body(patch)))
        }
        return Intent(Intent.ACTION_VIEW, Uri.parse(url))
            .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
    }

    /** Clipboard-friendly text fallback when the issue URL itself is too long
     * for an `ACTION_VIEW` Intent (browser URL limits are larger than typical
     * issue bodies, but a user with thousands of edits could trip ~2 MB).
     * Copies the patch body to the system clipboard and shows a toast. */
    fun copyToClipboard(context: Context, patch: TimingsPatch) {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager
        clipboard?.setPrimaryClip(ClipData.newPlainText("Timings patch", body(patch)))
        Toast.makeText(context, "Patch copied", Toast.LENGTH_SHORT).show()
    }
}